DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS grams CASCADE;

CREATE TABLE users(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  profile_photo TEXT
);

CREATE TABLE grams(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  photo_url TEXT NOT NULL,
  caption TEXT,
  tags TEXT,
  user_id BIGINT REFERENCES users(id)
);
